{"name": "测试数据：【 1532341，111111a，{except_result}，10000，token】", "status": "broken", "statusDetails": {"message": "TypeError: post() got multiple values for argument 'url'", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x0000023745B06A58>\nusername = '1532341', password = '111111a', login_type = 1, except_code = 10000\nexcept_msg = 'token'\nheaders = {'Content-Type': 'application/json', 'select_nation_id': 'RU'}\nurl = '/idserverhq/public/auth/login'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, login_type, except_code, except_msg, headers, url\",\n                             api_data[\"test_login_user\"])\n    \n    def test_login_user(self, username, password, login_type, except_code, except_msg,headers,url):\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       result = login_user(username, password, login_type,headers,url)\n\ntest_03_login.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\operation\\user.py:103: in login_user\n    res = user.login(json=payload, headers=header, url=url)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api.user.User object at 0x0000023745269390>\nkwargs = {'headers': {'Content-Type': 'application/json', 'select_nation_id': 'RU'}, 'json': {'login_type': 1, 'password': '111111a', 'username': '1532341'}, 'url': '/idserverhq/public/auth/login'}\nurl = '/idserverhq/public/auth/login'\n\n    def login(self, **kwargs):\n        url = dict(**kwargs).get(\"url\")\n>       return self.post(url,**kwargs)\nE       TypeError: post() got multiple values for argument 'url'\n\n..\\..\\api\\user.py:28: TypeError"}, "description": "该用例是针对获取用户登录接口的测试", "attachments": [{"name": "log", "source": "c205335f-2d46-4d93-92a9-ff94347e62ff-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'1532341'"}, {"name": "password", "value": "'111111a'"}, {"name": "login_type", "value": "1"}, {"name": "except_code", "value": "10000"}, {"name": "except_msg", "value": "'token'"}, {"name": "headers", "value": "{'Content-Type': 'application/json', 'select_nation_id': 'RU'}"}, {"name": "url", "value": "'/idserverhq/public/auth/login'"}], "start": 1669427362903, "stop": 1669427362903, "uuid": "3a67695d-4232-4d9d-a7f9-591b2338ebc5", "historyId": "0de4ecfae382e86437822b0a68f446dd", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "severity", "value": "normal"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "lijuan"}, {"name": "thread", "value": "4740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}